package com.kh.admin.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class Finance implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.order_sn
     *
     * @mbggenerated
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.pay_platform_order_sn
     *
     * @mbggenerated
     */
    private String payPlatformOrderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.liquidator_order_sn
     *
     * @mbggenerated
     */
    private String liquidatorOrderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.store_id
     *
     * @mbggenerated
     */
    private String storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.liquidator_merchant_id
     *
     * @mbggenerated
     */
    private String liquidatorMerchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.liquidator_id
     *
     * @mbggenerated
     */
    private String liquidatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.notify_url
     *
     * @mbggenerated
     */
    private String notifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.order_type
     *
     * @mbggenerated
     */
    private Integer orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.pay_platform_type
     *
     * @mbggenerated
     */
    private Integer payPlatformType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.real_money
     *
     * @mbggenerated
     */
    private BigDecimal realMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.net_money
     *
     * @mbggenerated
     */
    private BigDecimal netMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.pay_platform_rate
     *
     * @mbggenerated
     */
    private BigDecimal payPlatformRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.pay_platform_fee
     *
     * @mbggenerated
     */
    private BigDecimal payPlatformFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.bank_commission_rate
     *
     * @mbggenerated
     */
    private BigDecimal bankCommissionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.bank_commission_fee
     *
     * @mbggenerated
     */
    private BigDecimal bankCommissionFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.liquidator_commission_rate
     *
     * @mbggenerated
     */
    private BigDecimal liquidatorCommissionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.liquidator_commission_fee
     *
     * @mbggenerated
     */
    private BigDecimal liquidatorCommissionFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.pay_status
     *
     * @mbggenerated
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.pay_time
     *
     * @mbggenerated
     */
    private Long payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.update_time
     *
     * @mbggenerated
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.create_day
     *
     * @mbggenerated
     */
    private Integer createDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.pay_day
     *
     * @mbggenerated
     */
    private Integer payDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.sub_mch_id
     *
     * @mbggenerated
     */
    private String subMchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.bank_type
     *
     * @mbggenerated
     */
    private String bankType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.is_credit
     *
     * @mbggenerated
     */
    private Integer isCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table finance
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.order_sn
     *
     * @return the value of finance.order_sn
     *
     * @mbggenerated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.order_sn
     *
     * @param orderSn the value for finance.order_sn
     *
     * @mbggenerated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.pay_platform_order_sn
     *
     * @return the value of finance.pay_platform_order_sn
     *
     * @mbggenerated
     */
    public String getPayPlatformOrderSn() {
        return payPlatformOrderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.pay_platform_order_sn
     *
     * @param payPlatformOrderSn the value for finance.pay_platform_order_sn
     *
     * @mbggenerated
     */
    public void setPayPlatformOrderSn(String payPlatformOrderSn) {
        this.payPlatformOrderSn = payPlatformOrderSn == null ? null : payPlatformOrderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.liquidator_order_sn
     *
     * @return the value of finance.liquidator_order_sn
     *
     * @mbggenerated
     */
    public String getLiquidatorOrderSn() {
        return liquidatorOrderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.liquidator_order_sn
     *
     * @param liquidatorOrderSn the value for finance.liquidator_order_sn
     *
     * @mbggenerated
     */
    public void setLiquidatorOrderSn(String liquidatorOrderSn) {
        this.liquidatorOrderSn = liquidatorOrderSn == null ? null : liquidatorOrderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.store_id
     *
     * @return the value of finance.store_id
     *
     * @mbggenerated
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.store_id
     *
     * @param storeId the value for finance.store_id
     *
     * @mbggenerated
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.liquidator_merchant_id
     *
     * @return the value of finance.liquidator_merchant_id
     *
     * @mbggenerated
     */
    public String getLiquidatorMerchantId() {
        return liquidatorMerchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.liquidator_merchant_id
     *
     * @param liquidatorMerchantId the value for finance.liquidator_merchant_id
     *
     * @mbggenerated
     */
    public void setLiquidatorMerchantId(String liquidatorMerchantId) {
        this.liquidatorMerchantId = liquidatorMerchantId == null ? null : liquidatorMerchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.liquidator_id
     *
     * @return the value of finance.liquidator_id
     *
     * @mbggenerated
     */
    public String getLiquidatorId() {
        return liquidatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.liquidator_id
     *
     * @param liquidatorId the value for finance.liquidator_id
     *
     * @mbggenerated
     */
    public void setLiquidatorId(String liquidatorId) {
        this.liquidatorId = liquidatorId == null ? null : liquidatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.notify_url
     *
     * @return the value of finance.notify_url
     *
     * @mbggenerated
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.notify_url
     *
     * @param notifyUrl the value for finance.notify_url
     *
     * @mbggenerated
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.order_type
     *
     * @return the value of finance.order_type
     *
     * @mbggenerated
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.order_type
     *
     * @param orderType the value for finance.order_type
     *
     * @mbggenerated
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.pay_platform_type
     *
     * @return the value of finance.pay_platform_type
     *
     * @mbggenerated
     */
    public Integer getPayPlatformType() {
        return payPlatformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.pay_platform_type
     *
     * @param payPlatformType the value for finance.pay_platform_type
     *
     * @mbggenerated
     */
    public void setPayPlatformType(Integer payPlatformType) {
        this.payPlatformType = payPlatformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.real_money
     *
     * @return the value of finance.real_money
     *
     * @mbggenerated
     */
    public BigDecimal getRealMoney() {
        return realMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.real_money
     *
     * @param realMoney the value for finance.real_money
     *
     * @mbggenerated
     */
    public void setRealMoney(BigDecimal realMoney) {
        this.realMoney = realMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.net_money
     *
     * @return the value of finance.net_money
     *
     * @mbggenerated
     */
    public BigDecimal getNetMoney() {
        return netMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.net_money
     *
     * @param netMoney the value for finance.net_money
     *
     * @mbggenerated
     */
    public void setNetMoney(BigDecimal netMoney) {
        this.netMoney = netMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.pay_platform_rate
     *
     * @return the value of finance.pay_platform_rate
     *
     * @mbggenerated
     */
    public BigDecimal getPayPlatformRate() {
        return payPlatformRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.pay_platform_rate
     *
     * @param payPlatformRate the value for finance.pay_platform_rate
     *
     * @mbggenerated
     */
    public void setPayPlatformRate(BigDecimal payPlatformRate) {
        this.payPlatformRate = payPlatformRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.pay_platform_fee
     *
     * @return the value of finance.pay_platform_fee
     *
     * @mbggenerated
     */
    public BigDecimal getPayPlatformFee() {
        return payPlatformFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.pay_platform_fee
     *
     * @param payPlatformFee the value for finance.pay_platform_fee
     *
     * @mbggenerated
     */
    public void setPayPlatformFee(BigDecimal payPlatformFee) {
        this.payPlatformFee = payPlatformFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.bank_commission_rate
     *
     * @return the value of finance.bank_commission_rate
     *
     * @mbggenerated
     */
    public BigDecimal getBankCommissionRate() {
        return bankCommissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.bank_commission_rate
     *
     * @param bankCommissionRate the value for finance.bank_commission_rate
     *
     * @mbggenerated
     */
    public void setBankCommissionRate(BigDecimal bankCommissionRate) {
        this.bankCommissionRate = bankCommissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.bank_commission_fee
     *
     * @return the value of finance.bank_commission_fee
     *
     * @mbggenerated
     */
    public BigDecimal getBankCommissionFee() {
        return bankCommissionFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.bank_commission_fee
     *
     * @param bankCommissionFee the value for finance.bank_commission_fee
     *
     * @mbggenerated
     */
    public void setBankCommissionFee(BigDecimal bankCommissionFee) {
        this.bankCommissionFee = bankCommissionFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.liquidator_commission_rate
     *
     * @return the value of finance.liquidator_commission_rate
     *
     * @mbggenerated
     */
    public BigDecimal getLiquidatorCommissionRate() {
        return liquidatorCommissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.liquidator_commission_rate
     *
     * @param liquidatorCommissionRate the value for finance.liquidator_commission_rate
     *
     * @mbggenerated
     */
    public void setLiquidatorCommissionRate(BigDecimal liquidatorCommissionRate) {
        this.liquidatorCommissionRate = liquidatorCommissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.liquidator_commission_fee
     *
     * @return the value of finance.liquidator_commission_fee
     *
     * @mbggenerated
     */
    public BigDecimal getLiquidatorCommissionFee() {
        return liquidatorCommissionFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.liquidator_commission_fee
     *
     * @param liquidatorCommissionFee the value for finance.liquidator_commission_fee
     *
     * @mbggenerated
     */
    public void setLiquidatorCommissionFee(BigDecimal liquidatorCommissionFee) {
        this.liquidatorCommissionFee = liquidatorCommissionFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.pay_status
     *
     * @return the value of finance.pay_status
     *
     * @mbggenerated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.pay_status
     *
     * @param payStatus the value for finance.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.pay_time
     *
     * @return the value of finance.pay_time
     *
     * @mbggenerated
     */
    public Long getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.pay_time
     *
     * @param payTime the value for finance.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Long payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.create_time
     *
     * @return the value of finance.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.create_time
     *
     * @param createTime the value for finance.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.update_time
     *
     * @return the value of finance.update_time
     *
     * @mbggenerated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.update_time
     *
     * @param updateTime the value for finance.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.create_day
     *
     * @return the value of finance.create_day
     *
     * @mbggenerated
     */
    public Integer getCreateDay() {
        return createDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.create_day
     *
     * @param createDay the value for finance.create_day
     *
     * @mbggenerated
     */
    public void setCreateDay(Integer createDay) {
        this.createDay = createDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.pay_day
     *
     * @return the value of finance.pay_day
     *
     * @mbggenerated
     */
    public Integer getPayDay() {
        return payDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.pay_day
     *
     * @param payDay the value for finance.pay_day
     *
     * @mbggenerated
     */
    public void setPayDay(Integer payDay) {
        this.payDay = payDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.sub_mch_id
     *
     * @return the value of finance.sub_mch_id
     *
     * @mbggenerated
     */
    public String getSubMchId() {
        return subMchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.sub_mch_id
     *
     * @param subMchId the value for finance.sub_mch_id
     *
     * @mbggenerated
     */
    public void setSubMchId(String subMchId) {
        this.subMchId = subMchId == null ? null : subMchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.bank_type
     *
     * @return the value of finance.bank_type
     *
     * @mbggenerated
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.bank_type
     *
     * @param bankType the value for finance.bank_type
     *
     * @mbggenerated
     */
    public void setBankType(String bankType) {
        this.bankType = bankType == null ? null : bankType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.is_credit
     *
     * @return the value of finance.is_credit
     *
     * @mbggenerated
     */
    public Integer getIsCredit() {
        return isCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.is_credit
     *
     * @param isCredit the value for finance.is_credit
     *
     * @mbggenerated
     */
    public void setIsCredit(Integer isCredit) {
        this.isCredit = isCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderSn=").append(orderSn);
        sb.append(", payPlatformOrderSn=").append(payPlatformOrderSn);
        sb.append(", liquidatorOrderSn=").append(liquidatorOrderSn);
        sb.append(", storeId=").append(storeId);
        sb.append(", liquidatorMerchantId=").append(liquidatorMerchantId);
        sb.append(", liquidatorId=").append(liquidatorId);
        sb.append(", notifyUrl=").append(notifyUrl);
        sb.append(", orderType=").append(orderType);
        sb.append(", payPlatformType=").append(payPlatformType);
        sb.append(", realMoney=").append(realMoney);
        sb.append(", netMoney=").append(netMoney);
        sb.append(", payPlatformRate=").append(payPlatformRate);
        sb.append(", payPlatformFee=").append(payPlatformFee);
        sb.append(", bankCommissionRate=").append(bankCommissionRate);
        sb.append(", bankCommissionFee=").append(bankCommissionFee);
        sb.append(", liquidatorCommissionRate=").append(liquidatorCommissionRate);
        sb.append(", liquidatorCommissionFee=").append(liquidatorCommissionFee);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", payTime=").append(payTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createDay=").append(createDay);
        sb.append(", payDay=").append(payDay);
        sb.append(", subMchId=").append(subMchId);
        sb.append(", bankType=").append(bankType);
        sb.append(", isCredit=").append(isCredit);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Finance other = (Finance) that;
        return (this.getOrderSn() == null ? other.getOrderSn() == null : this.getOrderSn().equals(other.getOrderSn()))
            && (this.getPayPlatformOrderSn() == null ? other.getPayPlatformOrderSn() == null : this.getPayPlatformOrderSn().equals(other.getPayPlatformOrderSn()))
            && (this.getLiquidatorOrderSn() == null ? other.getLiquidatorOrderSn() == null : this.getLiquidatorOrderSn().equals(other.getLiquidatorOrderSn()))
            && (this.getStoreId() == null ? other.getStoreId() == null : this.getStoreId().equals(other.getStoreId()))
            && (this.getLiquidatorMerchantId() == null ? other.getLiquidatorMerchantId() == null : this.getLiquidatorMerchantId().equals(other.getLiquidatorMerchantId()))
            && (this.getLiquidatorId() == null ? other.getLiquidatorId() == null : this.getLiquidatorId().equals(other.getLiquidatorId()))
            && (this.getNotifyUrl() == null ? other.getNotifyUrl() == null : this.getNotifyUrl().equals(other.getNotifyUrl()))
            && (this.getOrderType() == null ? other.getOrderType() == null : this.getOrderType().equals(other.getOrderType()))
            && (this.getPayPlatformType() == null ? other.getPayPlatformType() == null : this.getPayPlatformType().equals(other.getPayPlatformType()))
            && (this.getRealMoney() == null ? other.getRealMoney() == null : this.getRealMoney().equals(other.getRealMoney()))
            && (this.getNetMoney() == null ? other.getNetMoney() == null : this.getNetMoney().equals(other.getNetMoney()))
            && (this.getPayPlatformRate() == null ? other.getPayPlatformRate() == null : this.getPayPlatformRate().equals(other.getPayPlatformRate()))
            && (this.getPayPlatformFee() == null ? other.getPayPlatformFee() == null : this.getPayPlatformFee().equals(other.getPayPlatformFee()))
            && (this.getBankCommissionRate() == null ? other.getBankCommissionRate() == null : this.getBankCommissionRate().equals(other.getBankCommissionRate()))
            && (this.getBankCommissionFee() == null ? other.getBankCommissionFee() == null : this.getBankCommissionFee().equals(other.getBankCommissionFee()))
            && (this.getLiquidatorCommissionRate() == null ? other.getLiquidatorCommissionRate() == null : this.getLiquidatorCommissionRate().equals(other.getLiquidatorCommissionRate()))
            && (this.getLiquidatorCommissionFee() == null ? other.getLiquidatorCommissionFee() == null : this.getLiquidatorCommissionFee().equals(other.getLiquidatorCommissionFee()))
            && (this.getPayStatus() == null ? other.getPayStatus() == null : this.getPayStatus().equals(other.getPayStatus()))
            && (this.getPayTime() == null ? other.getPayTime() == null : this.getPayTime().equals(other.getPayTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreateDay() == null ? other.getCreateDay() == null : this.getCreateDay().equals(other.getCreateDay()))
            && (this.getPayDay() == null ? other.getPayDay() == null : this.getPayDay().equals(other.getPayDay()))
            && (this.getSubMchId() == null ? other.getSubMchId() == null : this.getSubMchId().equals(other.getSubMchId()))
            && (this.getBankType() == null ? other.getBankType() == null : this.getBankType().equals(other.getBankType()))
            && (this.getIsCredit() == null ? other.getIsCredit() == null : this.getIsCredit().equals(other.getIsCredit()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderSn() == null) ? 0 : getOrderSn().hashCode());
        result = prime * result + ((getPayPlatformOrderSn() == null) ? 0 : getPayPlatformOrderSn().hashCode());
        result = prime * result + ((getLiquidatorOrderSn() == null) ? 0 : getLiquidatorOrderSn().hashCode());
        result = prime * result + ((getStoreId() == null) ? 0 : getStoreId().hashCode());
        result = prime * result + ((getLiquidatorMerchantId() == null) ? 0 : getLiquidatorMerchantId().hashCode());
        result = prime * result + ((getLiquidatorId() == null) ? 0 : getLiquidatorId().hashCode());
        result = prime * result + ((getNotifyUrl() == null) ? 0 : getNotifyUrl().hashCode());
        result = prime * result + ((getOrderType() == null) ? 0 : getOrderType().hashCode());
        result = prime * result + ((getPayPlatformType() == null) ? 0 : getPayPlatformType().hashCode());
        result = prime * result + ((getRealMoney() == null) ? 0 : getRealMoney().hashCode());
        result = prime * result + ((getNetMoney() == null) ? 0 : getNetMoney().hashCode());
        result = prime * result + ((getPayPlatformRate() == null) ? 0 : getPayPlatformRate().hashCode());
        result = prime * result + ((getPayPlatformFee() == null) ? 0 : getPayPlatformFee().hashCode());
        result = prime * result + ((getBankCommissionRate() == null) ? 0 : getBankCommissionRate().hashCode());
        result = prime * result + ((getBankCommissionFee() == null) ? 0 : getBankCommissionFee().hashCode());
        result = prime * result + ((getLiquidatorCommissionRate() == null) ? 0 : getLiquidatorCommissionRate().hashCode());
        result = prime * result + ((getLiquidatorCommissionFee() == null) ? 0 : getLiquidatorCommissionFee().hashCode());
        result = prime * result + ((getPayStatus() == null) ? 0 : getPayStatus().hashCode());
        result = prime * result + ((getPayTime() == null) ? 0 : getPayTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreateDay() == null) ? 0 : getCreateDay().hashCode());
        result = prime * result + ((getPayDay() == null) ? 0 : getPayDay().hashCode());
        result = prime * result + ((getSubMchId() == null) ? 0 : getSubMchId().hashCode());
        result = prime * result + ((getBankType() == null) ? 0 : getBankType().hashCode());
        result = prime * result + ((getIsCredit() == null) ? 0 : getIsCredit().hashCode());
        return result;
    }
}