package com.kh.admin.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class LpRefundOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.order_sn
     *
     * @mbggenerated
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.liquidator_id
     *
     * @mbggenerated
     */
    private String liquidatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.store_id
     *
     * @mbggenerated
     */
    private String storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.liquidator_order_sn
     *
     * @mbggenerated
     */
    private String liquidatorOrderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.platform_order_sn
     *
     * @mbggenerated
     */
    private String platformOrderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.refund_no
     *
     * @mbggenerated
     */
    private String refundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.out_refund_no
     *
     * @mbggenerated
     */
    private String outRefundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.platform_refund_no
     *
     * @mbggenerated
     */
    private String platformRefundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.platform_type
     *
     * @mbggenerated
     */
    private Integer platformType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.order_money
     *
     * @mbggenerated
     */
    private BigDecimal orderMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.refund_money
     *
     * @mbggenerated
     */
    private BigDecimal refundMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.refund_status
     *
     * @mbggenerated
     */
    private Integer refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.remit_status
     *
     * @mbggenerated
     */
    private Integer remitStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.update_time
     *
     * @mbggenerated
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.pay_time
     *
     * @mbggenerated
     */
    private Long payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.bank_commission_rate
     *
     * @mbggenerated
     */
    private BigDecimal bankCommissionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.bank_commission_fee
     *
     * @mbggenerated
     */
    private BigDecimal bankCommissionFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.pay_platform_rate
     *
     * @mbggenerated
     */
    private BigDecimal payPlatformRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.pay_platform_fee
     *
     * @mbggenerated
     */
    private BigDecimal payPlatformFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.is_more_day
     *
     * @mbggenerated
     */
    private Integer isMoreDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.liquidator_commission_rate
     *
     * @mbggenerated
     */
    private BigDecimal liquidatorCommissionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.liquidator_commission_fee
     *
     * @mbggenerated
     */
    private BigDecimal liquidatorCommissionFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_refund_order.execute_status
     *
     * @mbggenerated
     */
    private Integer executeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lp_refund_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.order_sn
     *
     * @return the value of lp_refund_order.order_sn
     *
     * @mbggenerated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.order_sn
     *
     * @param orderSn the value for lp_refund_order.order_sn
     *
     * @mbggenerated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.liquidator_id
     *
     * @return the value of lp_refund_order.liquidator_id
     *
     * @mbggenerated
     */
    public String getLiquidatorId() {
        return liquidatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.liquidator_id
     *
     * @param liquidatorId the value for lp_refund_order.liquidator_id
     *
     * @mbggenerated
     */
    public void setLiquidatorId(String liquidatorId) {
        this.liquidatorId = liquidatorId == null ? null : liquidatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.store_id
     *
     * @return the value of lp_refund_order.store_id
     *
     * @mbggenerated
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.store_id
     *
     * @param storeId the value for lp_refund_order.store_id
     *
     * @mbggenerated
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.liquidator_order_sn
     *
     * @return the value of lp_refund_order.liquidator_order_sn
     *
     * @mbggenerated
     */
    public String getLiquidatorOrderSn() {
        return liquidatorOrderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.liquidator_order_sn
     *
     * @param liquidatorOrderSn the value for lp_refund_order.liquidator_order_sn
     *
     * @mbggenerated
     */
    public void setLiquidatorOrderSn(String liquidatorOrderSn) {
        this.liquidatorOrderSn = liquidatorOrderSn == null ? null : liquidatorOrderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.platform_order_sn
     *
     * @return the value of lp_refund_order.platform_order_sn
     *
     * @mbggenerated
     */
    public String getPlatformOrderSn() {
        return platformOrderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.platform_order_sn
     *
     * @param platformOrderSn the value for lp_refund_order.platform_order_sn
     *
     * @mbggenerated
     */
    public void setPlatformOrderSn(String platformOrderSn) {
        this.platformOrderSn = platformOrderSn == null ? null : platformOrderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.refund_no
     *
     * @return the value of lp_refund_order.refund_no
     *
     * @mbggenerated
     */
    public String getRefundNo() {
        return refundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.refund_no
     *
     * @param refundNo the value for lp_refund_order.refund_no
     *
     * @mbggenerated
     */
    public void setRefundNo(String refundNo) {
        this.refundNo = refundNo == null ? null : refundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.out_refund_no
     *
     * @return the value of lp_refund_order.out_refund_no
     *
     * @mbggenerated
     */
    public String getOutRefundNo() {
        return outRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.out_refund_no
     *
     * @param outRefundNo the value for lp_refund_order.out_refund_no
     *
     * @mbggenerated
     */
    public void setOutRefundNo(String outRefundNo) {
        this.outRefundNo = outRefundNo == null ? null : outRefundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.platform_refund_no
     *
     * @return the value of lp_refund_order.platform_refund_no
     *
     * @mbggenerated
     */
    public String getPlatformRefundNo() {
        return platformRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.platform_refund_no
     *
     * @param platformRefundNo the value for lp_refund_order.platform_refund_no
     *
     * @mbggenerated
     */
    public void setPlatformRefundNo(String platformRefundNo) {
        this.platformRefundNo = platformRefundNo == null ? null : platformRefundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.platform_type
     *
     * @return the value of lp_refund_order.platform_type
     *
     * @mbggenerated
     */
    public Integer getPlatformType() {
        return platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.platform_type
     *
     * @param platformType the value for lp_refund_order.platform_type
     *
     * @mbggenerated
     */
    public void setPlatformType(Integer platformType) {
        this.platformType = platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.order_money
     *
     * @return the value of lp_refund_order.order_money
     *
     * @mbggenerated
     */
    public BigDecimal getOrderMoney() {
        return orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.order_money
     *
     * @param orderMoney the value for lp_refund_order.order_money
     *
     * @mbggenerated
     */
    public void setOrderMoney(BigDecimal orderMoney) {
        this.orderMoney = orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.refund_money
     *
     * @return the value of lp_refund_order.refund_money
     *
     * @mbggenerated
     */
    public BigDecimal getRefundMoney() {
        return refundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.refund_money
     *
     * @param refundMoney the value for lp_refund_order.refund_money
     *
     * @mbggenerated
     */
    public void setRefundMoney(BigDecimal refundMoney) {
        this.refundMoney = refundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.refund_status
     *
     * @return the value of lp_refund_order.refund_status
     *
     * @mbggenerated
     */
    public Integer getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.refund_status
     *
     * @param refundStatus the value for lp_refund_order.refund_status
     *
     * @mbggenerated
     */
    public void setRefundStatus(Integer refundStatus) {
        this.refundStatus = refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.remit_status
     *
     * @return the value of lp_refund_order.remit_status
     *
     * @mbggenerated
     */
    public Integer getRemitStatus() {
        return remitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.remit_status
     *
     * @param remitStatus the value for lp_refund_order.remit_status
     *
     * @mbggenerated
     */
    public void setRemitStatus(Integer remitStatus) {
        this.remitStatus = remitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.create_time
     *
     * @return the value of lp_refund_order.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.create_time
     *
     * @param createTime the value for lp_refund_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.update_time
     *
     * @return the value of lp_refund_order.update_time
     *
     * @mbggenerated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.update_time
     *
     * @param updateTime the value for lp_refund_order.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.pay_time
     *
     * @return the value of lp_refund_order.pay_time
     *
     * @mbggenerated
     */
    public Long getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.pay_time
     *
     * @param payTime the value for lp_refund_order.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Long payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.bank_commission_rate
     *
     * @return the value of lp_refund_order.bank_commission_rate
     *
     * @mbggenerated
     */
    public BigDecimal getBankCommissionRate() {
        return bankCommissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.bank_commission_rate
     *
     * @param bankCommissionRate the value for lp_refund_order.bank_commission_rate
     *
     * @mbggenerated
     */
    public void setBankCommissionRate(BigDecimal bankCommissionRate) {
        this.bankCommissionRate = bankCommissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.bank_commission_fee
     *
     * @return the value of lp_refund_order.bank_commission_fee
     *
     * @mbggenerated
     */
    public BigDecimal getBankCommissionFee() {
        return bankCommissionFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.bank_commission_fee
     *
     * @param bankCommissionFee the value for lp_refund_order.bank_commission_fee
     *
     * @mbggenerated
     */
    public void setBankCommissionFee(BigDecimal bankCommissionFee) {
        this.bankCommissionFee = bankCommissionFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.pay_platform_rate
     *
     * @return the value of lp_refund_order.pay_platform_rate
     *
     * @mbggenerated
     */
    public BigDecimal getPayPlatformRate() {
        return payPlatformRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.pay_platform_rate
     *
     * @param payPlatformRate the value for lp_refund_order.pay_platform_rate
     *
     * @mbggenerated
     */
    public void setPayPlatformRate(BigDecimal payPlatformRate) {
        this.payPlatformRate = payPlatformRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.pay_platform_fee
     *
     * @return the value of lp_refund_order.pay_platform_fee
     *
     * @mbggenerated
     */
    public BigDecimal getPayPlatformFee() {
        return payPlatformFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.pay_platform_fee
     *
     * @param payPlatformFee the value for lp_refund_order.pay_platform_fee
     *
     * @mbggenerated
     */
    public void setPayPlatformFee(BigDecimal payPlatformFee) {
        this.payPlatformFee = payPlatformFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.is_more_day
     *
     * @return the value of lp_refund_order.is_more_day
     *
     * @mbggenerated
     */
    public Integer getIsMoreDay() {
        return isMoreDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.is_more_day
     *
     * @param isMoreDay the value for lp_refund_order.is_more_day
     *
     * @mbggenerated
     */
    public void setIsMoreDay(Integer isMoreDay) {
        this.isMoreDay = isMoreDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.liquidator_commission_rate
     *
     * @return the value of lp_refund_order.liquidator_commission_rate
     *
     * @mbggenerated
     */
    public BigDecimal getLiquidatorCommissionRate() {
        return liquidatorCommissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.liquidator_commission_rate
     *
     * @param liquidatorCommissionRate the value for lp_refund_order.liquidator_commission_rate
     *
     * @mbggenerated
     */
    public void setLiquidatorCommissionRate(BigDecimal liquidatorCommissionRate) {
        this.liquidatorCommissionRate = liquidatorCommissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.liquidator_commission_fee
     *
     * @return the value of lp_refund_order.liquidator_commission_fee
     *
     * @mbggenerated
     */
    public BigDecimal getLiquidatorCommissionFee() {
        return liquidatorCommissionFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.liquidator_commission_fee
     *
     * @param liquidatorCommissionFee the value for lp_refund_order.liquidator_commission_fee
     *
     * @mbggenerated
     */
    public void setLiquidatorCommissionFee(BigDecimal liquidatorCommissionFee) {
        this.liquidatorCommissionFee = liquidatorCommissionFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_refund_order.execute_status
     *
     * @return the value of lp_refund_order.execute_status
     *
     * @mbggenerated
     */
    public Integer getExecuteStatus() {
        return executeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_refund_order.execute_status
     *
     * @param executeStatus the value for lp_refund_order.execute_status
     *
     * @mbggenerated
     */
    public void setExecuteStatus(Integer executeStatus) {
        this.executeStatus = executeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_refund_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderSn=").append(orderSn);
        sb.append(", liquidatorId=").append(liquidatorId);
        sb.append(", storeId=").append(storeId);
        sb.append(", liquidatorOrderSn=").append(liquidatorOrderSn);
        sb.append(", platformOrderSn=").append(platformOrderSn);
        sb.append(", refundNo=").append(refundNo);
        sb.append(", outRefundNo=").append(outRefundNo);
        sb.append(", platformRefundNo=").append(platformRefundNo);
        sb.append(", platformType=").append(platformType);
        sb.append(", orderMoney=").append(orderMoney);
        sb.append(", refundMoney=").append(refundMoney);
        sb.append(", refundStatus=").append(refundStatus);
        sb.append(", remitStatus=").append(remitStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", payTime=").append(payTime);
        sb.append(", bankCommissionRate=").append(bankCommissionRate);
        sb.append(", bankCommissionFee=").append(bankCommissionFee);
        sb.append(", payPlatformRate=").append(payPlatformRate);
        sb.append(", payPlatformFee=").append(payPlatformFee);
        sb.append(", isMoreDay=").append(isMoreDay);
        sb.append(", liquidatorCommissionRate=").append(liquidatorCommissionRate);
        sb.append(", liquidatorCommissionFee=").append(liquidatorCommissionFee);
        sb.append(", executeStatus=").append(executeStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_refund_order
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LpRefundOrder other = (LpRefundOrder) that;
        return (this.getOrderSn() == null ? other.getOrderSn() == null : this.getOrderSn().equals(other.getOrderSn()))
            && (this.getLiquidatorId() == null ? other.getLiquidatorId() == null : this.getLiquidatorId().equals(other.getLiquidatorId()))
            && (this.getStoreId() == null ? other.getStoreId() == null : this.getStoreId().equals(other.getStoreId()))
            && (this.getLiquidatorOrderSn() == null ? other.getLiquidatorOrderSn() == null : this.getLiquidatorOrderSn().equals(other.getLiquidatorOrderSn()))
            && (this.getPlatformOrderSn() == null ? other.getPlatformOrderSn() == null : this.getPlatformOrderSn().equals(other.getPlatformOrderSn()))
            && (this.getRefundNo() == null ? other.getRefundNo() == null : this.getRefundNo().equals(other.getRefundNo()))
            && (this.getOutRefundNo() == null ? other.getOutRefundNo() == null : this.getOutRefundNo().equals(other.getOutRefundNo()))
            && (this.getPlatformRefundNo() == null ? other.getPlatformRefundNo() == null : this.getPlatformRefundNo().equals(other.getPlatformRefundNo()))
            && (this.getPlatformType() == null ? other.getPlatformType() == null : this.getPlatformType().equals(other.getPlatformType()))
            && (this.getOrderMoney() == null ? other.getOrderMoney() == null : this.getOrderMoney().equals(other.getOrderMoney()))
            && (this.getRefundMoney() == null ? other.getRefundMoney() == null : this.getRefundMoney().equals(other.getRefundMoney()))
            && (this.getRefundStatus() == null ? other.getRefundStatus() == null : this.getRefundStatus().equals(other.getRefundStatus()))
            && (this.getRemitStatus() == null ? other.getRemitStatus() == null : this.getRemitStatus().equals(other.getRemitStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getPayTime() == null ? other.getPayTime() == null : this.getPayTime().equals(other.getPayTime()))
            && (this.getBankCommissionRate() == null ? other.getBankCommissionRate() == null : this.getBankCommissionRate().equals(other.getBankCommissionRate()))
            && (this.getBankCommissionFee() == null ? other.getBankCommissionFee() == null : this.getBankCommissionFee().equals(other.getBankCommissionFee()))
            && (this.getPayPlatformRate() == null ? other.getPayPlatformRate() == null : this.getPayPlatformRate().equals(other.getPayPlatformRate()))
            && (this.getPayPlatformFee() == null ? other.getPayPlatformFee() == null : this.getPayPlatformFee().equals(other.getPayPlatformFee()))
            && (this.getIsMoreDay() == null ? other.getIsMoreDay() == null : this.getIsMoreDay().equals(other.getIsMoreDay()))
            && (this.getLiquidatorCommissionRate() == null ? other.getLiquidatorCommissionRate() == null : this.getLiquidatorCommissionRate().equals(other.getLiquidatorCommissionRate()))
            && (this.getLiquidatorCommissionFee() == null ? other.getLiquidatorCommissionFee() == null : this.getLiquidatorCommissionFee().equals(other.getLiquidatorCommissionFee()))
            && (this.getExecuteStatus() == null ? other.getExecuteStatus() == null : this.getExecuteStatus().equals(other.getExecuteStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_refund_order
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderSn() == null) ? 0 : getOrderSn().hashCode());
        result = prime * result + ((getLiquidatorId() == null) ? 0 : getLiquidatorId().hashCode());
        result = prime * result + ((getStoreId() == null) ? 0 : getStoreId().hashCode());
        result = prime * result + ((getLiquidatorOrderSn() == null) ? 0 : getLiquidatorOrderSn().hashCode());
        result = prime * result + ((getPlatformOrderSn() == null) ? 0 : getPlatformOrderSn().hashCode());
        result = prime * result + ((getRefundNo() == null) ? 0 : getRefundNo().hashCode());
        result = prime * result + ((getOutRefundNo() == null) ? 0 : getOutRefundNo().hashCode());
        result = prime * result + ((getPlatformRefundNo() == null) ? 0 : getPlatformRefundNo().hashCode());
        result = prime * result + ((getPlatformType() == null) ? 0 : getPlatformType().hashCode());
        result = prime * result + ((getOrderMoney() == null) ? 0 : getOrderMoney().hashCode());
        result = prime * result + ((getRefundMoney() == null) ? 0 : getRefundMoney().hashCode());
        result = prime * result + ((getRefundStatus() == null) ? 0 : getRefundStatus().hashCode());
        result = prime * result + ((getRemitStatus() == null) ? 0 : getRemitStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getPayTime() == null) ? 0 : getPayTime().hashCode());
        result = prime * result + ((getBankCommissionRate() == null) ? 0 : getBankCommissionRate().hashCode());
        result = prime * result + ((getBankCommissionFee() == null) ? 0 : getBankCommissionFee().hashCode());
        result = prime * result + ((getPayPlatformRate() == null) ? 0 : getPayPlatformRate().hashCode());
        result = prime * result + ((getPayPlatformFee() == null) ? 0 : getPayPlatformFee().hashCode());
        result = prime * result + ((getIsMoreDay() == null) ? 0 : getIsMoreDay().hashCode());
        result = prime * result + ((getLiquidatorCommissionRate() == null) ? 0 : getLiquidatorCommissionRate().hashCode());
        result = prime * result + ((getLiquidatorCommissionFee() == null) ? 0 : getLiquidatorCommissionFee().hashCode());
        result = prime * result + ((getExecuteStatus() == null) ? 0 : getExecuteStatus().hashCode());
        return result;
    }
}