package com.kh.admin.dao;

import com.kh.admin.model.KhUser;

public interface KhUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_user
     *
     * @mbggenerated
     */
    int insert(KhUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_user
     *
     * @mbggenerated
     */
    int insertSelective(KhUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_user
     *
     * @mbggenerated
     */
    KhUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KhUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KhUser record);
}